### ISSUE TITLE
Unable to npm install @cycle/core or @cycle/web

### ISSUE THREAD

**Issue by eschwartz** [cyclejs/cycle-core#152]
According to the docs:

>The recommended channel for downloading Cycle.js as a package is through npm, which follows the CommonJS spec. Create a new directory and run this inside that directory:

>```npm install @cycle/core @cycle/web```

However, when I try to install these packages, I get:
```
npm ERR! Darwin 14.4.0
npm ERR! argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "install" "@cycle/core"
npm ERR! node v1.8.2
npm ERR! npm  v2.9.0

npm ERR! Invalid name: "@cycle/core"
```

------

Here's the full debug log

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/iojs',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '@cycle/core',
1 verbose cli   '--verbose' ]
2 info using npm@2.9.0
3 info using node@v1.8.2
4 verbose install initial load of /Users/edanschwartz/workspace/tmp/package.json
5 warn package.json tmp@1.0.0 No description
6 warn package.json tmp@1.0.0 No repository field.
7 warn package.json tmp@1.0.0 No README data
8 verbose installManyTop reading scoped package data from /Users/edanschwartz/workspace/tmp/node_modules/cyclejs/package.json
9 verbose readDependencies loading dependencies from /Users/edanschwartz/workspace/tmp/package.json
10 silly cache add args [ '@cycle/core', null ]
11 verbose cache add spec @cycle/core
12 silly cache add parsed spec { raw: '@cycle/core',
12 silly cache add   scope: '@cycle',
12 silly cache add   name: '@cycle/core',
12 silly cache add   rawSpec: '',
12 silly cache add   spec: '*',
12 silly cache add   type: 'range' }
13 silly addNamed @cycle/core@*
14 verbose addNamed "*" is a valid semver range for @cycle/core
15 silly addNameRange { name: '@cycle/core', range: '*', hasData: false }
16 silly mapToRegistry name @cycle/core
17 silly mapToRegistry scope (from package name) @cycle
18 verbose mapToRegistry no registry URL found in name for scope @cycle
19 silly mapToRegistry using default registry
20 silly mapToRegistry registry https://registry.npmjs.org/
21 silly mapToRegistry uri https://registry.npmjs.org/@cycle%2fcore
22 verbose addNameRange registry:https://registry.npmjs.org/@cycle%2fcore not in flight; fetching
23 verbose request uri https://registry.npmjs.org/@cycle%2fcore
24 verbose request no auth needed
25 info attempt registry request try #1 at 09:09:36
26 verbose request id fee0c8239050807a
27 verbose etag "C2NOB6W4TE2TM534Y3ISS4QO2"
28 http request GET https://registry.npmjs.org/@cycle%2fcore
29 http 304 https://registry.npmjs.org/@cycle%2fcore
30 silly get cb [ 304,
30 silly get   { date: 'Fri, 10 Jul 2015 14:09:36 GMT',
30 silly get     via: '1.1 varnish',
30 silly get     'cache-control': 'max-age=0',
30 silly get     etag: '"C2NOB6W4TE2TM534Y3ISS4QO2"',
30 silly get     age: '0',
30 silly get     connection: 'keep-alive',
30 silly get     'x-served-by': 'cache-dfw1828-DFW',
30 silly get     'x-cache': 'MISS',
30 silly get     'x-cache-hits': '0',
30 silly get     'x-timer': 'S1436537376.471409,VS0,VE329',
30 silly get     vary: 'Accept' } ]
31 verbose etag https://registry.npmjs.org/@cycle%2fcore from cache
32 verbose get saving @cycle/core to /Users/edanschwartz/.npm/registry.npmjs.org/_40cycle_252fcore/.cache.json
33 silly addNameRange number 2 { name: '@cycle/core', range: '*', hasData: true }
34 silly addNameRange versions [ '@cycle/core', [ '1.0.0-rc1', '1.0.0' ] ]
35 silly addNamed @cycle/core@1.0.0
36 verbose addNamed "1.0.0" is a plain semver version for @cycle/core
37 verbose stack Error: Invalid name: "@cycle/core"
37 verbose stack     at ensureValidName (/usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/fixer.js:300:15)
37 verbose stack     at Object.module.exports.fixNameField (/usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/fixer.js:204:5)
37 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/normalize.js:30:38
37 verbose stack     at Array.forEach (native)
37 verbose stack     at normalize (/usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/normalize.js:29:15)
37 verbose stack     at final (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:338:5)
37 verbose stack     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:113:5)
37 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:178:20
37 verbose stack     at FSReqWrap.readFileAfterOpen [as oncomplete] (evalmachine.<anonymous>:305:5)
38 verbose cwd /Users/edanschwartz/workspace/tmp
39 error Darwin 14.4.0
40 error argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "install" "@cycle/core" "--verbose"
41 error node v1.8.2
42 error npm  v2.9.0
43 error Invalid name: "@cycle/core"
44 error If you need help, you may report this error at:
44 error     <https://github.com/npm/npm/issues>
45 verbose exit [ 1, true ]

**Comment by staltz** [comment]
Update npm version and try again. I should write on the docs which npm version supports scoped packages "@org/package" (cant remember right now which version that is).

**Comment by eschwartz** [comment]
Same thing with npm v2.12.1:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/iojs',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '@cycle/core',
1 verbose cli   '--verbose' ]
2 info using npm@2.12.1
3 info using node@v2.3.4
4 verbose install initial load of /Users/edanschwartz/workspace/tmp/package.json
5 warn package.json tmp@1.0.0 No description
6 warn package.json tmp@1.0.0 No repository field.
7 warn package.json tmp@1.0.0 No README data
8 verbose installManyTop reading scoped package data from /Users/edanschwartz/workspace/tmp/node_modules/cyclejs/package.json
9 verbose readDependencies loading dependencies from /Users/edanschwartz/workspace/tmp/package.json
10 silly cache add args [ '@cycle/core', null ]
11 verbose cache add spec @cycle/core
12 silly cache add parsed spec { raw: '@cycle/core',
12 silly cache add   scope: '@cycle',
12 silly cache add   name: '@cycle/core',
12 silly cache add   rawSpec: '',
12 silly cache add   spec: '*',
12 silly cache add   type: 'range' }
13 silly addNamed @cycle/core@*
14 verbose addNamed "*" is a valid semver range for @cycle/core
15 silly addNameRange { name: '@cycle/core', range: '*', hasData: false }
16 silly mapToRegistry name @cycle/core
17 silly mapToRegistry scope (from package name) @cycle
18 verbose mapToRegistry no registry URL found in name for scope @cycle
19 silly mapToRegistry using default registry
20 silly mapToRegistry registry https://registry.npmjs.org/
21 silly mapToRegistry uri https://registry.npmjs.org/@cycle%2fcore
22 verbose addNameRange registry:https://registry.npmjs.org/@cycle%2fcore not in flight; fetching
23 verbose request uri https://registry.npmjs.org/@cycle%2fcore
24 verbose request no auth needed
25 info attempt registry request try #1 at 13:51:54
26 verbose request id 12898d54075f94bb
27 verbose etag "C2NOB6W4TE2TM534Y3ISS4QO2"
28 http request GET https://registry.npmjs.org/@cycle%2fcore
29 http 304 https://registry.npmjs.org/@cycle%2fcore
30 silly get cb [ 304,
30 silly get   { date: 'Fri, 10 Jul 2015 18:51:54 GMT',
30 silly get     via: '1.1 varnish',
30 silly get     'cache-control': 'max-age=0',
30 silly get     etag: '"C2NOB6W4TE2TM534Y3ISS4QO2"',
30 silly get     age: '0',
30 silly get     connection: 'keep-alive',
30 silly get     'x-served-by': 'cache-atl6227-ATL',
30 silly get     'x-cache': 'MISS',
30 silly get     'x-cache-hits': '0',
30 silly get     'x-timer': 'S1436554314.666635,VS0,VE148',
30 silly get     vary: 'Accept' } ]
31 verbose etag https://registry.npmjs.org/@cycle%2fcore from cache
32 verbose get saving @cycle/core to /Users/edanschwartz/.npm/registry.npmjs.org/_40cycle_252fcore/.cache.json
33 silly addNameRange number 2 { name: '@cycle/core', range: '*', hasData: true }
34 silly addNameRange versions [ '@cycle/core', [ '1.0.0-rc1', '1.0.0' ] ]
35 silly addNamed @cycle/core@1.0.0
36 verbose addNamed "1.0.0" is a plain semver version for @cycle/core
37 verbose stack Error: Invalid name: "@cycle/core"
37 verbose stack     at ensureValidName (/usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/fixer.js:300:15)
37 verbose stack     at Object.module.exports.fixNameField (/usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/fixer.js:204:5)
37 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/normalize.js:30:38
37 verbose stack     at Array.forEach (native)
37 verbose stack     at normalize (/usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/normalize.js:29:15)
37 verbose stack     at final (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:338:5)
37 verbose stack     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:113:5)
37 verbose stack     at ReadFileContext.callback (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:178:20)
37 verbose stack     at FSReqWrap.readFileAfterOpen [as oncomplete] (evalmachine.<anonymous>:303:13)
38 verbose cwd /Users/edanschwartz/workspace/tmp
39 error Darwin 14.4.0
40 error argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "install" "@cycle/core" "--verbose"
41 error node v2.3.4
42 error npm  v2.12.1
43 error Invalid name: "@cycle/core"
44 error If you need help, you may report this error at:
44 error     <https://github.com/npm/npm/issues>
45 verbose exit [ 1, true ]
```

**Comment by staltz** [comment]
This shouldn't be any problem with the Cycle Core or Web packages. I can confirm from my side that with different (and recent) versions of npm, `npm install @cycle/core` doesn't report "Invalid name". Also I'm using a Mac OS X, just like you seem to.

It _could_ be: iojs-related, or a bug in normalize-package-data/lib/fixer.js:300:15, or something else.

My verbose logs:
```
npm info it worked if it ends with ok
npm verb cli [ 'node',
npm verb cli   '/usr/local/bin/npm',
npm verb cli   'install',
npm verb cli   '@cycle/core',
npm verb cli   '--verbose' ]
npm info using npm@2.13.0
npm info using node@v0.10.26
npm verb install initial load of /Users/amed/Hobby/cycle/bug152/package.json
npm verb readDependencies loading dependencies from /Users/amed/Hobby/cycle/bug152/package.json
npm verb cache add spec @cycle/core
npm verb addNamed "*" is a valid semver range for @cycle/core
npm verb mapToRegistry no registry URL found in name for scope @cycle
npm verb addNameRange registry:https://registry.npmjs.org/@cycle%2fcore not in flight; fetching
npm verb request uri https://registry.npmjs.org/@cycle%2fcore
npm verb request no auth needed
npm info attempt registry request try #1 at 23:59:37
npm verb request using bearer token for auth
npm verb request id d44d0bf0d540e9dc
npm verb etag "C2NOB6W4TE2TM534Y3ISS4QO2"
npm http request GET https://registry.npmjs.org/@cycle%2fcore
npm http 304 https://registry.npmjs.org/@cycle%2fcore
npm verb etag https://registry.npmjs.org/@cycle%2fcore from cache
npm verb get saving @cycle/core to /Users/amed/.npm/registry.npmjs.org/_40cycle_252fcore/.cache.json
npm verb addNamed "1.0.0" is a plain semver version for @cycle/core
npm verb afterAdd /Users/amed/.npm/@cycle/core/1.0.0/package/package.json not in flight; writing
npm verb afterAdd /Users/amed/.npm/@cycle/core/1.0.0/package/package.json written
npm info install @cycle/core@1.0.0 into /Users/amed/Hobby/cycle/bug152
npm info installOne @cycle/core@1.0.0
npm verb installOne of @cycle/core to /Users/amed/Hobby/cycle/bug152 not in flight; installing
npm verb lock using /Users/amed/.npm/_locks/cycle-core-4f9d78f690dd291a.lock for /Users/amed/Hobby/cycle/bug152/node_modules/@cycle/core
npm verb unbuild node_modules/@cycle/core
npm verb gentlyRm don't care about contents; nuking /Users/amed/Hobby/cycle/bug152/node_modules/@cycle/core
npm verb tar unpack /Users/amed/.npm/@cycle/core/1.0.0/package.tgz
npm verb tar unpacking to /Users/amed/Hobby/cycle/bug152/node_modules/@cycle/core
npm verb gentlyRm don't care about contents; nuking /Users/amed/Hobby/cycle/bug152/node_modules/@cycle/core
npm verb write writing to /Users/amed/Hobby/cycle/bug152/node_modules/@cycle/core/package.json
npm info preinstall @cycle/core@1.0.0
npm verb readDependencies loading dependencies from /Users/amed/Hobby/cycle/bug152/node_modules/@cycle/core/package.json
npm verb readDependencies loading dependencies from /Users/amed/Hobby/cycle/bug152/node_modules/@cycle/core/package.json
npm verb cache add spec rx@2.5.3
npm verb addNamed "2.5.3" is a plain semver version for rx
npm verb addNameVersion registry:https://registry.npmjs.org/rx not in flight; fetching
npm verb request uri https://registry.npmjs.org/rx
npm verb request no auth needed
npm info attempt registry request try #1 at 23:59:39
npm verb request using bearer token for auth
npm verb etag "531BNQB4R9JLEPPJK09K8Q6GY"
npm http request GET https://registry.npmjs.org/rx
npm http 304 https://registry.npmjs.org/rx
npm verb etag https://registry.npmjs.org/rx from cache
npm verb get saving rx to /Users/amed/.npm/registry.npmjs.org/rx/.cache.json
npm verb afterAdd /Users/amed/.npm/rx/2.5.3/package/package.json not in flight; writing
npm verb afterAdd /Users/amed/.npm/rx/2.5.3/package/package.json written
npm info install rx@2.5.3 into /Users/amed/Hobby/cycle/bug152/node_modules/@cycle/core
npm info installOne rx@2.5.3
npm verb installOne of rx to /Users/amed/Hobby/cycle/bug152/node_modules/@cycle/core not in flight; installing
npm verb lock using /Users/amed/.npm/_locks/rx-a85392f8e01950ab.lock for /Users/amed/Hobby/cycle/bug152/node_modules/@cycle/core/node_modules/rx
npm verb unbuild node_modules/@cycle/core/node_modules/rx
npm verb gentlyRm don't care about contents; nuking /Users/amed/Hobby/cycle/bug152/node_modules/@cycle/core/node_modules/rx
npm verb tar unpack /Users/amed/.npm/rx/2.5.3/package.tgz
npm verb tar unpacking to /Users/amed/Hobby/cycle/bug152/node_modules/@cycle/core/node_modules/rx
npm verb gentlyRm don't care about contents; nuking /Users/amed/Hobby/cycle/bug152/node_modules/@cycle/core/node_modules/rx
npm verb write writing to /Users/amed/Hobby/cycle/bug152/node_modules/@cycle/core/node_modules/rx/package.json
npm info preinstall rx@2.5.3
npm verb readDependencies loading dependencies from /Users/amed/Hobby/cycle/bug152/node_modules/@cycle/core/node_modules/rx/package.json
npm verb readDependencies loading dependencies from /Users/amed/Hobby/cycle/bug152/node_modules/@cycle/core/node_modules/rx/package.json
npm verb about to build /Users/amed/Hobby/cycle/bug152/node_modules/@cycle/core/node_modules/rx
npm info build /Users/amed/Hobby/cycle/bug152/node_modules/@cycle/core/node_modules/rx
npm info linkStuff rx@2.5.3
npm verb linkBins rx@2.5.3
npm verb linkMans rx@2.5.3
npm verb rebuildBundles rx@2.5.3
npm info install rx@2.5.3
npm info postinstall rx@2.5.3
npm verb unlock done using /Users/amed/.npm/_locks/rx-a85392f8e01950ab.lock for /Users/amed/Hobby/cycle/bug152/node_modules/@cycle/core/node_modules/rx
npm verb about to build /Users/amed/Hobby/cycle/bug152/node_modules/@cycle/core
npm info build /Users/amed/Hobby/cycle/bug152/node_modules/@cycle/core
npm info linkStuff @cycle/core@1.0.0
npm verb linkBins @cycle/core@1.0.0
npm verb linkMans @cycle/core@1.0.0
npm verb rebuildBundles @cycle/core@1.0.0
npm verb rebuildBundles [ 'rx' ]
npm info install @cycle/core@1.0.0
npm info postinstall @cycle/core@1.0.0
npm verb unlock done using /Users/amed/.npm/_locks/cycle-core-4f9d78f690dd291a.lock for /Users/amed/Hobby/cycle/bug152/node_modules/@cycle/core
npm verb validateInstall loading /Users/amed/Hobby/cycle/bug152/package.json for validation
@cycle/core@1.0.0 node_modules/@cycle/core
└── rx@2.5.3
npm verb exit [ 0, true ]
npm info ok
```

**Comment by pH200** [comment]
This issue is also stopping me from testing with Travis CI w/ node 0.10

```
$ nvm install 0.10
######################################################################## 100.0%
Now using node v0.10.40
$ node --version
v0.10.40
$ npm --version
1.4.28
$ nvm --version
0.23.3
5.94s$ npm install 
npm ERR! Error: version not found: core : cycle/core
npm ERR!     at RegClient.<anonymous> (/home/travis/.nvm/v0.10.40/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:308:14)
npm ERR!     at Request._callback (/home/travis/.nvm/v0.10.40/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:246:65)
npm ERR!     at Request.self.callback (/home/travis/.nvm/v0.10.40/lib/node_modules/npm/node_modules/request/request.js:236:22)
npm ERR!     at Request.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/home/travis/.nvm/v0.10.40/lib/node_modules/npm/node_modules/request/request.js:1142:14)
npm ERR!     at Request.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (/home/travis/.nvm/v0.10.40/lib/node_modules/npm/node_modules/request/request.js:1096:12)
npm ERR!     at IncomingMessage.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:944:16
npm ERR!     at process._tickCallback (node.js:448:13)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>
npm ERR! System Linux 3.13.0-40-generic
npm ERR! command "/home/travis/.nvm/v0.10.40/bin/node" "/home/travis/.nvm/v0.10.40/bin/npm" "install"
npm ERR! cwd /home/travis/build/pH200/cycle-react
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.28
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/travis/build/pH200/cycle-react/npm-debug.log
npm ERR! not ok code 0
```

**Comment by staltz** [comment]
@pH200 Your problem is easier to solve

```
$ npm --version
1.4.28
```

Too old npm. 2.7 or higher needed: https://docs.npmjs.com/getting-started/scoped-packages

**Comment by eschwartz** [comment]
> v2.7 or higher needed: https://docs.npmjs.com/getting-started/scoped-packages

I was using v2.9, and the scoped package wasn't working. 

I'd updated node, thinking that it would update npm to the latest version. But I guess you have to use npm to update npm:

`npm update -g npm`

That brought me up to v2.13.0, which worked fine.

**Comment by nobleach** [comment]
I've tried with 2.13.5 and 3.5.3. Neither one is capable of installing these packages. Is there any other way to get them installed?
